"""Guards that the generated dependency manifests still match uv.lock.

``pyproject.toml`` + ``uv.lock`` are the source of truth. ``requirements.txt``
and ``requirements-test.txt`` are **generated** by ``uv export`` and kept only so
``pip install -r`` still works on a host where uv is unavailable — which is not
hypothetical here: the production box is a shared PythonAnywhere account where
dependencies are installed by hand.

That fallback is worth having only if it is accurate. Before uv these two files
and ``pyproject.toml`` were three hand-maintained copies of the same list with
nothing keeping them in sync, and the resulting skew is what left production
running kurigram 2.2.23 against code that required 2.2.26. Re-locking without
re-exporting would quietly recreate exactly that gap, so these tests fail on it.

Deliberately dependency-free: no uv at test time, and no ``tomllib`` either —
that is 3.11+, while this project supports 3.10 (which is what the server runs).
Plain regex over both files is enough to compare pinned versions.
"""

import re
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[2]
LOCK = ROOT / "uv.lock"
RUNTIME_REQS = ROOT / "requirements.txt"
TEST_REQS = ROOT / "requirements-test.txt"
PYPROJECT = ROOT / "pyproject.toml"

# `name==version`, ignoring any environment marker (`; python_full_version < …`)
# and uv's indented `# via …` annotation lines.
_PIN_RE = re.compile(r"^([A-Za-z0-9][A-Za-z0-9._-]*)==([^\s;#]+)", re.MULTILINE)
_LOCK_PKG_RE = re.compile(
    r'^\[\[package\]\]\nname = "([^"]+)"\nversion = "([^"]+)"', re.MULTILINE
)
# pyproject pins are indented and quoted, and may carry an extras bracket:
#     "python-telegram-bot[rate-limiter]==22.8",
# so they need their own pattern — a line-anchored one silently matches nothing
# here, which made this guard vacuously pass until a mutation check caught it.
_PYPROJECT_PIN_RE = re.compile(
    r'"([A-Za-z0-9][A-Za-z0-9._-]*)(?:\[[^\]]*\])?==([^"\s;]+)"'
)


def _canon(name: str) -> str:
    """PEP 503 normalization — uv writes `python-telegram-bot`, pins may vary."""
    return re.sub(r"[-_.]+", "-", name).lower()


def _pins(path: Path) -> dict:
    return {
        _canon(name): version for name, version in _PIN_RE.findall(path.read_text())
    }


def _locked() -> dict:
    return {
        _canon(name): version
        for name, version in _LOCK_PKG_RE.findall(LOCK.read_text())
    }


def test_the_manifests_exist():
    # A missing lock means someone removed uv without regenerating the pins.
    for path in (LOCK, RUNTIME_REQS, TEST_REQS, PYPROJECT):
        assert path.is_file(), f"{path.name} is missing"


def test_generated_files_say_they_are_generated():
    """A hand-edit to these is lost on the next export, so they must say so."""
    for path in (RUNTIME_REQS, TEST_REQS):
        head = path.read_text()[:200].lower()
        assert "autogenerated" in head or "generated" in head, (
            f"{path.name} lost its generated-by header"
        )


@pytest.mark.parametrize("path", [RUNTIME_REQS, TEST_REQS], ids=lambda p: p.name)
def test_exported_pins_match_the_lockfile(path):
    """Every exported pin must be the version uv.lock resolved.

    Fails when someone changes a dependency and re-locks without re-running
    `uv export` — the stale requirements file would then install a different
    set than the lock promises, on exactly the host that has no uv to notice.
    """
    locked = _locked()
    assert locked, "parsed no packages out of uv.lock"
    mismatched = {
        name: (version, locked.get(name))
        for name, version in _pins(path).items()
        if locked.get(name) != version
    }
    assert not mismatched, (
        f"{path.name} is out of sync with uv.lock "
        f"(name: exported vs locked): {mismatched}. "
        "Re-run: uv export --frozen --no-dev --no-hashes --no-emit-project "
        "-o requirements.txt  (and without --no-dev for requirements-test.txt)"
    )


def test_runtime_manifest_carries_no_test_tooling():
    """`--no-dev` must actually hold: pytest has no business on the server."""
    runtime = _pins(RUNTIME_REQS)
    for name in ("pytest", "pytest-asyncio", "pytest-cov"):
        assert name not in runtime, f"{name} leaked into requirements.txt"


def test_test_manifest_is_a_superset_of_runtime():
    runtime, tests = _pins(RUNTIME_REQS), _pins(TEST_REQS)
    missing = {n for n in runtime if n not in tests}
    assert not missing, f"requirements-test.txt is missing runtime pins: {missing}"
    assert "pytest" in tests


def test_pyproject_pins_are_what_the_lock_resolved():
    """Catches a dependency edited in pyproject.toml without re-locking."""
    locked = _locked()
    # Only the `name==version` pins; `>=` floors are ranges, not assertions.
    declared = {
        _canon(name): version
        for name, version in _PYPROJECT_PIN_RE.findall(PYPROJECT.read_text())
    }
    # Without this the test passes when the regex matches nothing at all.
    assert len(declared) >= 5, f"parsed too few pins out of pyproject.toml: {declared}"
    drifted = {
        name: (version, locked.get(name))
        for name, version in declared.items()
        if locked.get(name) != version
    }
    assert not drifted, (
        f"pyproject.toml pins disagree with uv.lock: {drifted}. Re-run `uv lock`."
    )
